
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning



namespace ZeNerd.DAL.Context
{





    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]

    public class AspNetUsers
    {


        public string Id { get; set; }

        public string Email { get; set; }

        public bool EmailConfirmed { get; set; }

        public string PasswordHash { get; set; }

        public string SecurityStamp { get; set; }

        public string PhoneNumber { get; set; }

        public bool PhoneNumberConfirmed { get; set; }

        public bool TwoFactorEnabled { get; set; }

        public System.DateTime? LockoutEndDateUtc { get; set; }

        public bool LockoutEnabled { get; set; }

        public int AccessFailedCount { get; set; }

        public string UserName { get; set; }






        public virtual System.Collections.Generic.ICollection<AspNetRoles> AspNetRoles { get; set; }


        public virtual System.Collections.Generic.ICollection<AspNetUserClaims> AspNetUserClaims { get; set; }


        public virtual System.Collections.Generic.ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }




        public AspNetUsers()
        {


            AspNetUserClaims = new System.Collections.Generic.List<AspNetUserClaims>();

            AspNetUserLogins = new System.Collections.Generic.List<AspNetUserLogins>();

            AspNetRoles = new System.Collections.Generic.List<AspNetRoles>();
        }

    }



}
// </auto-generated>
