
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning



namespace ZeNerd.DAL.Context
{



    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]

    public class GrupoUsuarioConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<GrupoUsuario>
    {
        public GrupoUsuarioConfiguration()
            : this("dbo")
        {
        }

        public GrupoUsuarioConfiguration(string schema)
        {

            ToTable("grupo_usuario", schema);

            HasKey(x => x.Id);



            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            Property(x => x.Descricao).HasColumnName(@"descricao").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);



        }
    }



}
// </auto-generated>
