
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning



namespace ZeNerd.DAL.Context
{



    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]

    public class MoradorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Morador>
    {
        public MoradorConfiguration()
            : this("dbo")
        {
        }

        public MoradorConfiguration(string schema)
        {

            ToTable("morador", schema);

            HasKey(x => x.Id);



            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            Property(x => x.Nome).HasColumnName(@"nome").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Uf).HasColumnName(@"UF").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Municipio).HasColumnName(@"municipio").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Distrito).HasColumnName(@"distrito").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Subdistrito).HasColumnName(@"subdistrito").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Setor).HasColumnName(@"setor").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.NumeroQuadra).HasColumnName(@"numero_quadra").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.NumeroFace).HasColumnName(@"numero_face").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.SeqEndereco).HasColumnName(@"seq_endereco").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.SeqColetivo).HasColumnName(@"seq_coletivo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.SeqEspecie).HasColumnName(@"seq_especie").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.TipoEspecieDomicilioOcupado).HasColumnName(@"tipo_especie_domicilio_ocupado").HasColumnType("int").IsOptional();

            Property(x => x.TipoDomicilio).HasColumnName(@"tipo_domicilio").HasColumnType("int").IsOptional();

            Property(x => x.QuantidadePessoasDomicilio).HasColumnName(@"quantidade_pessoas_domicilio").HasColumnType("int").IsOptional();

            Property(x => x.TipoSexo).HasColumnName(@"tipo_sexo").HasColumnType("int").IsOptional();

            Property(x => x.DataNascimento).HasColumnName(@"data_nascimento").HasColumnType("datetime").IsOptional();

            Property(x => x.TipoParantesco).HasColumnName(@"tipo_parantesco").HasColumnType("int").IsOptional();

            Property(x => x.TipoEtinoRacial).HasColumnName(@"tipo_etino_racial").HasColumnType("int").IsOptional();

            Property(x => x.TipoPessoaIndigena).HasColumnName(@"tipo_pessoa_indigena").HasColumnType("int").IsOptional();

            Property(x => x.Etinia).HasColumnName(@"etinia").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.TipoFalaLinguaIndigena).HasColumnName(@"tipo_fala_lingua_indigena").HasColumnType("int").IsOptional();

            Property(x => x.LinguaIndigenaPrimeira).HasColumnName(@"lingua_indigena_primeira").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.LinguaIndigenaSegunda).HasColumnName(@"lingua_indigena_segunda").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.TipoLinguaPortuquesa).HasColumnName(@"tipo_lingua_portuquesa").HasColumnType("int").IsOptional();

            Property(x => x.TipoQuilombolas).HasColumnName(@"tipo_quilombolas").HasColumnType("int").IsOptional();

            Property(x => x.TipoRegistroCivil).HasColumnName(@"tipo_registro_civil").HasColumnType("int").IsOptional();

            Property(x => x.TipoEducacao).HasColumnName(@"tipo_educacao").HasColumnType("int").IsOptional();

            Property(x => x.NomeComunidade).HasColumnName(@"nome_comunidade").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Latitude).HasColumnName(@"latitude").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Longitude).HasColumnName(@"longitude").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Email).HasColumnName(@"email").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Arquivo).HasColumnName(@"arquivo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Telefone).HasColumnName(@"telefone").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);





            HasOptional(a => a.TipoDomicilio_TipoDomicilio).WithMany(b => b.Morador).HasForeignKey(c => c.TipoDomicilio).WillCascadeOnDelete(false);

            HasOptional(a => a.TipoEducacao_TipoEducacao).WithMany(b => b.Morador).HasForeignKey(c => c.TipoEducacao).WillCascadeOnDelete(false);

            HasOptional(a => a.TipoEspecieDomicilioOcupado_TipoEspecieDomicilioOcupado).WithMany(b => b.Morador).HasForeignKey(c => c.TipoEspecieDomicilioOcupado).WillCascadeOnDelete(false);

            HasOptional(a => a.TipoEtinoRacial_TipoEtinoRacial).WithMany(b => b.Morador).HasForeignKey(c => c.TipoEtinoRacial).WillCascadeOnDelete(false);

            HasOptional(a => a.TipoFalaLinguaIndigena_TipoFalaLinguaIndigena).WithMany(b => b.Morador).HasForeignKey(c => c.TipoFalaLinguaIndigena).WillCascadeOnDelete(false);

            HasOptional(a => a.TipoLinguaPortuquesa_TipoLinguaPortuquesa).WithMany(b => b.Morador).HasForeignKey(c => c.TipoLinguaPortuquesa).WillCascadeOnDelete(false);

            HasOptional(a => a.TipoParantesco_TipoParantesco).WithMany(b => b.Morador).HasForeignKey(c => c.TipoParantesco).WillCascadeOnDelete(false);

            HasOptional(a => a.TipoPessoaIndigena_TipoPessoaIndigena).WithMany(b => b.Morador).HasForeignKey(c => c.TipoPessoaIndigena).WillCascadeOnDelete(false);

            HasOptional(a => a.TipoQuilombolas_TipoQuilombolas).WithMany(b => b.Morador).HasForeignKey(c => c.TipoQuilombolas).WillCascadeOnDelete(false);

            HasOptional(a => a.TipoRegistroCivil_TipoRegistroCivil).WithMany(b => b.Morador).HasForeignKey(c => c.TipoRegistroCivil).WillCascadeOnDelete(false);

            HasOptional(a => a.TipoSexo_TipoSexo).WithMany(b => b.Morador).HasForeignKey(c => c.TipoSexo).WillCascadeOnDelete(false);


        }
    }



}
// </auto-generated>
