
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning



namespace ZeNerd.DAL.Context
{





    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]

    public class Morador
    {


        public int Id { get; set; }

        public string Nome { get; set; }

        public string Uf { get; set; }

        public string Municipio { get; set; }

        public string Distrito { get; set; }

        public string Subdistrito { get; set; }

        public string Setor { get; set; }

        public string NumeroQuadra { get; set; }

        public string NumeroFace { get; set; }

        public string SeqEndereco { get; set; }

        public string SeqColetivo { get; set; }

        public string SeqEspecie { get; set; }

        public int? TipoEspecieDomicilioOcupado { get; set; }

        public int? TipoDomicilio { get; set; }

        public int? QuantidadePessoasDomicilio { get; set; }

        public int? TipoSexo { get; set; }

        public System.DateTime? DataNascimento { get; set; }

        public int? TipoParantesco { get; set; }

        public int? TipoEtinoRacial { get; set; }

        public int? TipoPessoaIndigena { get; set; }

        public string Etinia { get; set; }

        public int? TipoFalaLinguaIndigena { get; set; }

        public string LinguaIndigenaPrimeira { get; set; }

        public string LinguaIndigenaSegunda { get; set; }

        public int? TipoLinguaPortuquesa { get; set; }

        public int? TipoQuilombolas { get; set; }

        public int? TipoRegistroCivil { get; set; }

        public int? TipoEducacao { get; set; }

        public string NomeComunidade { get; set; }

        public string Latitude { get; set; }

        public string Longitude { get; set; }

        public string Email { get; set; }

        public string Arquivo { get; set; }

        public string Telefone { get; set; }








        public virtual TipoDomicilio TipoDomicilio_TipoDomicilio { get; set; }



        public virtual TipoEducacao TipoEducacao_TipoEducacao { get; set; }



        public virtual TipoEspecieDomicilioOcupado TipoEspecieDomicilioOcupado_TipoEspecieDomicilioOcupado { get; set; }



        public virtual TipoEtinoRacial TipoEtinoRacial_TipoEtinoRacial { get; set; }



        public virtual TipoFalaLinguaIndigena TipoFalaLinguaIndigena_TipoFalaLinguaIndigena { get; set; }



        public virtual TipoLinguaPortuquesa TipoLinguaPortuquesa_TipoLinguaPortuquesa { get; set; }



        public virtual TipoParantesco TipoParantesco_TipoParantesco { get; set; }



        public virtual TipoPessoaIndigena TipoPessoaIndigena_TipoPessoaIndigena { get; set; }



        public virtual TipoQuilombolas TipoQuilombolas_TipoQuilombolas { get; set; }



        public virtual TipoRegistroCivil TipoRegistroCivil_TipoRegistroCivil { get; set; }



        public virtual TipoSexo TipoSexo_TipoSexo { get; set; }


    }



}
// </auto-generated>
