
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning



namespace ZeNerd.DAL.Context
{



    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]

    public class RotaDestinoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RotaDestino>
    {
        public RotaDestinoConfiguration()
            : this("dbo")
        {
        }

        public RotaDestinoConfiguration(string schema)
        {

            ToTable("rota_destino", schema);

            HasKey(x => x.Id);



            Property(x => x.Id).HasColumnName(@"id").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            Property(x => x.Endereco).HasColumnName(@"endereco").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);

            Property(x => x.Latitude).HasColumnName(@"latitude").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);

            Property(x => x.Longitude).HasColumnName(@"longitude").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);

            Property(x => x.Zoom).HasColumnName(@"zoom").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);

            Property(x => x.UsuarioId).HasColumnName(@"usuario_id").HasColumnType("bigint").IsOptional();

            Property(x => x.Data).HasColumnName(@"data").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);



        }
    }



}
// </auto-generated>
