
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning



namespace ZeNerd.DAL.Context
{



    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]

    public class UsuarioConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Usuario>
    {
        public UsuarioConfiguration()
            : this("dbo")
        {
        }

        public UsuarioConfiguration(string schema)
        {

            ToTable("usuario", schema);

            HasKey(x => new { x.Id, x.Nome, x.Senha, x.TipoUsuario, x.StatusCadastro, x.Ativo, x.DataCriacao, x.DataAtualizacao });



            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);

            Property(x => x.Nome).HasColumnName(@"nome").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            Property(x => x.Cpf).HasColumnName(@"cpf").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Celular).HasColumnName(@"celular").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Email).HasColumnName(@"email").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Senha).HasColumnName(@"senha").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            Property(x => x.Login).HasColumnName(@"login").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Cep).HasColumnName(@"cep").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Rua).HasColumnName(@"rua").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Bairro).HasColumnName(@"bairro").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Cidade).HasColumnName(@"cidade").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Estado).HasColumnName(@"estado").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Numero).HasColumnName(@"numero").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Complemento).HasColumnName(@"complemento").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.TipoUsuario).HasColumnName(@"tipo_usuario").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            Property(x => x.UrlFotoCnh).HasColumnName(@"url_foto_cnh").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);

            Property(x => x.UrlFotoSelfie).HasColumnName(@"url_foto_selfie").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);

            Property(x => x.Banco).HasColumnName(@"banco").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Agencia).HasColumnName(@"agencia").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Conta).HasColumnName(@"conta").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.Digito).HasColumnName(@"digito").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.StatusCadastro).HasColumnName(@"status_cadastro").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            Property(x => x.Ativo).HasColumnName(@"ativo").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            Property(x => x.DataCriacao).HasColumnName(@"data_criacao").HasColumnType("datetime").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            Property(x => x.DataAtualizacao).HasColumnName(@"data_atualizacao").HasColumnType("timestamp").IsRequired().IsFixedLength().HasMaxLength(8).IsRowVersion().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            Property(x => x.Foto).HasColumnName(@"foto").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            Property(x => x.PlayerId).HasColumnName(@"player_id").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);



        }
    }



}
// </auto-generated>
